/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import Componentes.Mensajes;

/**
 *
 * @author ADMIN
 */
public class dlgGestPerfiles extends javax.swing.JDialog {

    /**
     * Creates new form dlgGestPerfiles
     */
    public dlgGestPerfiles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Oscuro = new org.edisoncor.gui.panel.PanelImage();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new newscomponents.RSButtonBigIcon_new();
        btnActualizar = new newscomponents.RSButtonBigIcon_new();
        btnEliminar = new newscomponents.RSButtonBigIcon_new();
        btnEliminar1 = new newscomponents.RSButtonBigIcon_new();
        btnSalir = new newscomponents.RSButtonBigIcon_new();
        jPanel3 = new javax.swing.JPanel();
        rSCheckBox2 = new rojerusan.RSCheckBox();
        rSCheckBox3 = new rojerusan.RSCheckBox();
        rSCheckBox4 = new rojerusan.RSCheckBox();
        rSCheckBox6 = new rojerusan.RSCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rSCheckBox7 = new rojerusan.RSCheckBox();
        rSCheckBox8 = new rojerusan.RSCheckBox();
        rSCheckBox9 = new rojerusan.RSCheckBox();
        rSCheckBox10 = new rojerusan.RSCheckBox();
        rSCheckBox11 = new rojerusan.RSCheckBox();
        rSCheckBox12 = new rojerusan.RSCheckBox();
        rSCheckBox13 = new rojerusan.RSCheckBox();
        rSCheckBox14 = new rojerusan.RSCheckBox();
        rSCheckBox15 = new rojerusan.RSCheckBox();
        rSCheckBox16 = new rojerusan.RSCheckBox();
        rSCheckBox17 = new rojerusan.RSCheckBox();
        rSCheckBox18 = new rojerusan.RSCheckBox();
        rSCheckBox19 = new rojerusan.RSCheckBox();
        jPanel12 = new javax.swing.JPanel();
        rSCheckBox20 = new rojerusan.RSCheckBox();
        rSCheckBox21 = new rojerusan.RSCheckBox();
        jPanel13 = new javax.swing.JPanel();
        rSCheckBox22 = new rojerusan.RSCheckBox();
        rSCheckBox23 = new rojerusan.RSCheckBox();
        rSCheckBox24 = new rojerusan.RSCheckBox();
        jPanel14 = new javax.swing.JPanel();
        rSCheckBox25 = new rojerusan.RSCheckBox();
        rSCheckBox26 = new rojerusan.RSCheckBox();
        jPanel15 = new javax.swing.JPanel();
        rSCheckBox27 = new rojerusan.RSCheckBox();
        rSCheckBox28 = new rojerusan.RSCheckBox();
        rSCheckBox29 = new rojerusan.RSCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        rSCheckBox30 = new rojerusan.RSCheckBox();
        rSCheckBox31 = new rojerusan.RSCheckBox();
        rSCheckBox32 = new rojerusan.RSCheckBox();
        rSCheckBox33 = new rojerusan.RSCheckBox();
        rSCheckBox34 = new rojerusan.RSCheckBox();
        rSCheckBox35 = new rojerusan.RSCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        rSCheckBox36 = new rojerusan.RSCheckBox();
        rSCheckBox37 = new rojerusan.RSCheckBox();
        rSCheckBox38 = new rojerusan.RSCheckBox();
        rSCheckBox39 = new rojerusan.RSCheckBox();
        rSCheckBox40 = new rojerusan.RSCheckBox();
        rSCheckBox41 = new rojerusan.RSCheckBox();
        rSCheckBox42 = new rojerusan.RSCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Oscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/0-102-102.png"))); // NOI18N
        Oscuro.setPreferredSize(new java.awt.Dimension(690, 418));
        Oscuro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnNuevo.setBackground(new java.awt.Color(0, 102, 102));
        btnNuevo.setBorder(null);
        btnNuevo.setText("NUEVO");
        btnNuevo.setBgHover(new java.awt.Color(0, 153, 153));
        btnNuevo.setFocusPainted(false);
        btnNuevo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnNuevo.setIconTextGap(0);
        btnNuevo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_BOX);
        btnNuevo.setPixels(0);
        btnNuevo.setSizeIcon(40.0F);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        btnNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnNuevoKeyPressed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnActualizar.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizar.setBorder(null);
        btnActualizar.setText("MODIFICAR");
        btnActualizar.setBgHover(new java.awt.Color(0, 153, 153));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnActualizar.setIconTextGap(0);
        btnActualizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnActualizar.setPixels(0);
        btnActualizar.setSizeIcon(40.0F);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        btnActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnActualizarKeyPressed(evt);
            }
        });
        jPanel2.add(btnActualizar);

        btnEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar.setBorder(null);
        btnEliminar.setText("GUARDAR");
        btnEliminar.setBgHover(new java.awt.Color(0, 153, 153));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnEliminar.setIconTextGap(0);
        btnEliminar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnEliminar.setPixels(0);
        btnEliminar.setSizeIcon(40.0F);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEliminarKeyPressed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        btnEliminar1.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar1.setBorder(null);
        btnEliminar1.setText("CANCELAR");
        btnEliminar1.setBgHover(new java.awt.Color(0, 153, 153));
        btnEliminar1.setFocusPainted(false);
        btnEliminar1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnEliminar1.setIconTextGap(0);
        btnEliminar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnEliminar1.setPixels(0);
        btnEliminar1.setSizeIcon(40.0F);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        btnEliminar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEliminar1KeyPressed(evt);
            }
        });
        jPanel2.add(btnEliminar1);

        Oscuro.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 19, 280, 56));

        btnSalir.setBackground(new java.awt.Color(0, 102, 102));
        btnSalir.setBorder(null);
        btnSalir.setBgHover(new java.awt.Color(255, 0, 0));
        btnSalir.setFocusPainted(false);
        btnSalir.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnSalir.setIconTextGap(0);
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnSalir.setPixels(0);
        btnSalir.setSizeIcon(15.0F);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalirKeyPressed(evt);
            }
        });
        Oscuro.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 0, 15, 15));

        jPanel1.add(Oscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 76));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPCIONES DE OPERACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox2.setText("Nuevo");
        rSCheckBox2.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox2.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox2.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jPanel3.add(rSCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 100, 23));

        rSCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox3.setText("Modificar");
        rSCheckBox3.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox3.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox3.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jPanel3.add(rSCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 35, 100, 23));

        rSCheckBox4.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox4.setText("Eliminar/Anular");
        rSCheckBox4.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox4.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox4.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jPanel3.add(rSCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 35, 130, 23));

        rSCheckBox6.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox6.setText("Re-imprimir");
        rSCheckBox6.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox6.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox6.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jPanel3.add(rSCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 35, 100, 23));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 470, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU Y SUB-MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSCheckBox7.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox7.setText("Mantenimiento");
        rSCheckBox7.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox7.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rSCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCheckBox7ActionPerformed(evt);
            }
        });

        rSCheckBox8.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox8.setText("Informaciones generales y auxiliares");
        rSCheckBox8.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox8.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox8.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox9.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox9.setText("Gestionar empresa");
        rSCheckBox9.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox9.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox9.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox10.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox10.setText("Gestionar sucursales");
        rSCheckBox10.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox10.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox10.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox11.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox11.setText("Gestionar Timbrado");
        rSCheckBox11.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox11.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox11.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox12.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox12.setText("Gestionar Punto de Emisión");
        rSCheckBox12.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox12.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox12.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox13.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox13.setText("Gestionar Ciudades");
        rSCheckBox13.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox13.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox13.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox14.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox14.setText("Gestionar Clasificación");
        rSCheckBox14.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox14.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox14.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox15.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox15.setText("Gestionar Unidad de medida");
        rSCheckBox15.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox15.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox15.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox16.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox16.setText("Gestionar Impuesto");
        rSCheckBox16.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox16.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox16.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox17.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox17.setText("Gestionar motivos");
        rSCheckBox17.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox17.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox17.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox18.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox18.setText("Gestionar motivos de ingresos");
        rSCheckBox18.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox18.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox18.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox19.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox19.setText("Gestionar motivos de gastos");
        rSCheckBox19.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox19.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox19.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rSCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rSCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rSCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rSCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(rSCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(rSCheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(rSCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(rSCheckBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(rSCheckBox17, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(rSCheckBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(rSCheckBox18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))))
                            .addComponent(rSCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSCheckBox20.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox20.setText("Puntos de Control & Logística");
        rSCheckBox20.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox20.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox20.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rSCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCheckBox20ActionPerformed(evt);
            }
        });

        rSCheckBox21.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox21.setText("Gestionar  Puntos de Control & Logistica");
        rSCheckBox21.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox21.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox21.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSCheckBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSCheckBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSCheckBox22.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox22.setText("Recurso Humano");
        rSCheckBox22.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox22.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox22.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rSCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCheckBox22ActionPerformed(evt);
            }
        });

        rSCheckBox23.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox23.setText("Gestionar de Funcionarios");
        rSCheckBox23.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox23.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox23.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox24.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox24.setText("Comisiones");
        rSCheckBox24.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox24.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox24.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSCheckBox24, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSCheckBox23, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSCheckBox23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSCheckBox25.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox25.setText("Proveedores");
        rSCheckBox25.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox25.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox25.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rSCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCheckBox25ActionPerformed(evt);
            }
        });

        rSCheckBox26.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox26.setText("Gestionar Proveedores");
        rSCheckBox26.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox26.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox26.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSCheckBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSCheckBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSCheckBox27.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox27.setText("Clientes");
        rSCheckBox27.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox27.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox27.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rSCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCheckBox27ActionPerformed(evt);
            }
        });

        rSCheckBox28.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox28.setText("Gestionar Clientes");
        rSCheckBox28.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox28.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox28.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox29.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox29.setText("Generar Reportes");
        rSCheckBox29.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox29.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox29.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSCheckBox29, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSCheckBox28, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSCheckBox28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSCheckBox29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mantenimieto", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSCheckBox30.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox30.setText("Movimiento Diario");
        rSCheckBox30.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox30.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox30.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rSCheckBox30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCheckBox30ActionPerformed(evt);
            }
        });

        rSCheckBox31.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox31.setText("Inicializar Movimiento Diario (Caja)");
        rSCheckBox31.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox31.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox31.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox32.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox32.setText("Finalizar Movimiento Diario (Cierre de caja)");
        rSCheckBox32.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox32.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox32.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox33.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox33.setText("Generar Reportes");
        rSCheckBox33.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox33.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox33.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox34.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox34.setText("Mov. Diario (Cierre de caja)");
        rSCheckBox34.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox34.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox34.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox35.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox35.setText("Reporte total de ventas ");
        rSCheckBox35.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox35.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox35.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSCheckBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rSCheckBox32, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(rSCheckBox31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSCheckBox33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSCheckBox35, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBox34, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSCheckBox31, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox32, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox35, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimiento Diario", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSCheckBox36.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox36.setText("Gastos e Ingresos");
        rSCheckBox36.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox36.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox36.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rSCheckBox36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCheckBox36ActionPerformed(evt);
            }
        });

        rSCheckBox37.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox37.setText("Registrar Ingresos y/o Cobranzas");
        rSCheckBox37.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox37.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox37.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox38.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox38.setText("Finalizar Movimiento Diario (Cierre de caja)");
        rSCheckBox38.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox38.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox38.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox39.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox39.setText("Gestionar todos los Gastos Diarios");
        rSCheckBox39.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox39.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox39.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox40.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox40.setText("Mov. Diario (Cierre de caja)");
        rSCheckBox40.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox40.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox40.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox41.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox41.setText("Reporte total de ventas ");
        rSCheckBox41.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox41.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox41.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        rSCheckBox42.setForeground(new java.awt.Color(0, 0, 0));
        rSCheckBox42.setText("Generar Reportes");
        rSCheckBox42.setColorCheck(new java.awt.Color(0, 102, 102));
        rSCheckBox42.setColorUnCheck(new java.awt.Color(0, 0, 0));
        rSCheckBox42.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSCheckBox36, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSCheckBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBox40, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rSCheckBox38, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(rSCheckBox37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSCheckBox39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSCheckBox42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSCheckBox36, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSCheckBox37, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox38, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox39, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox42, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox40, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCheckBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gastos e Ingresos", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel11);

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 890, 370));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 910, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNuevoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoKeyPressed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnActualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnActualizarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarKeyPressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int rpta = Mensajes.confirmar("¿Seguro que desea salir del formulario?");
        if (rpta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirKeyPressed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnEliminar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar1KeyPressed

    private void rSCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCheckBox7ActionPerformed

    private void rSCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCheckBox20ActionPerformed

    private void rSCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCheckBox22ActionPerformed

    private void rSCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCheckBox25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCheckBox25ActionPerformed

    private void rSCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCheckBox27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCheckBox27ActionPerformed

    private void rSCheckBox30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCheckBox30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCheckBox30ActionPerformed

    private void rSCheckBox36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCheckBox36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCheckBox36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgGestPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgGestPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgGestPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgGestPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgGestPerfiles dialog = new dlgGestPerfiles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage Oscuro;
    private newscomponents.RSButtonBigIcon_new btnActualizar;
    public static newscomponents.RSButtonBigIcon_new btnEliminar;
    public static newscomponents.RSButtonBigIcon_new btnEliminar1;
    public static newscomponents.RSButtonBigIcon_new btnNuevo;
    public static newscomponents.RSButtonBigIcon_new btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private rojerusan.RSCheckBox rSCheckBox10;
    private rojerusan.RSCheckBox rSCheckBox11;
    private rojerusan.RSCheckBox rSCheckBox12;
    private rojerusan.RSCheckBox rSCheckBox13;
    private rojerusan.RSCheckBox rSCheckBox14;
    private rojerusan.RSCheckBox rSCheckBox15;
    private rojerusan.RSCheckBox rSCheckBox16;
    private rojerusan.RSCheckBox rSCheckBox17;
    private rojerusan.RSCheckBox rSCheckBox18;
    private rojerusan.RSCheckBox rSCheckBox19;
    private rojerusan.RSCheckBox rSCheckBox2;
    private rojerusan.RSCheckBox rSCheckBox20;
    private rojerusan.RSCheckBox rSCheckBox21;
    private rojerusan.RSCheckBox rSCheckBox22;
    private rojerusan.RSCheckBox rSCheckBox23;
    private rojerusan.RSCheckBox rSCheckBox24;
    private rojerusan.RSCheckBox rSCheckBox25;
    private rojerusan.RSCheckBox rSCheckBox26;
    private rojerusan.RSCheckBox rSCheckBox27;
    private rojerusan.RSCheckBox rSCheckBox28;
    private rojerusan.RSCheckBox rSCheckBox29;
    private rojerusan.RSCheckBox rSCheckBox3;
    private rojerusan.RSCheckBox rSCheckBox30;
    private rojerusan.RSCheckBox rSCheckBox31;
    private rojerusan.RSCheckBox rSCheckBox32;
    private rojerusan.RSCheckBox rSCheckBox33;
    private rojerusan.RSCheckBox rSCheckBox34;
    private rojerusan.RSCheckBox rSCheckBox35;
    private rojerusan.RSCheckBox rSCheckBox36;
    private rojerusan.RSCheckBox rSCheckBox37;
    private rojerusan.RSCheckBox rSCheckBox38;
    private rojerusan.RSCheckBox rSCheckBox39;
    private rojerusan.RSCheckBox rSCheckBox4;
    private rojerusan.RSCheckBox rSCheckBox40;
    private rojerusan.RSCheckBox rSCheckBox41;
    private rojerusan.RSCheckBox rSCheckBox42;
    private rojerusan.RSCheckBox rSCheckBox6;
    private rojerusan.RSCheckBox rSCheckBox7;
    private rojerusan.RSCheckBox rSCheckBox8;
    private rojerusan.RSCheckBox rSCheckBox9;
    // End of variables declaration//GEN-END:variables
}
